package br.com.leoferolive.nossalista.listitem.repository;

import br.com.leoferolive.nossalista.list.domain.SharedList;
import br.com.leoferolive.nossalista.list.repository.ListRepository;
import br.com.leoferolive.nossalista.listitem.domain.ListItem;
import br.com.leoferolive.nossalista.user.domain.AuthProvider;
import br.com.leoferolive.nossalista.user.domain.Role;
import br.com.leoferolive.nossalista.user.domain.User;
import br.com.leoferolive.nossalista.support.AbstractPostgresIT;
import br.com.leoferolive.nossalista.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import jakarta.persistence.EntityManager;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for ListItemRepository and validation of constraints.
 *
 * <p>Estende {@link AbstractPostgresIT}: roda contra PostgreSQL real
 * (Testcontainers), não H2 — ver T1 da Onda 2 (honestidade de métrica).</p>
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class ListItemRepositoryTest extends AbstractPostgresIT {

    @Autowired
    private ListItemRepository listItemRepository;

    @Autowired
    private ListRepository listRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private EntityManager entityManager;

    private User testUser;
    private SharedList testList;

    @BeforeEach
    void setUp() {
        // Create and persist test user - @PrePersist will set ID and timestamps
        testUser = new User();
        testUser.setUsername("testuser_" + System.currentTimeMillis());
        testUser.setEmail("test_" + System.currentTimeMillis() + "@example.com");
        testUser.setAuthProvider(AuthProvider.EMAIL);
        testUser.setPassword("$2a$10$dummyHashForTesting");
        testUser.setRole(Role.USER);
        testUser = userRepository.saveAndFlush(testUser);

        // Create and persist test list
        testList = new SharedList();
        testList.setName("Test List");
        testList.setTypeId(1); // Shopping
        testList.setOwner(testUser);
        testList = listRepository.saveAndFlush(testList);
    }

    @Test
    void shouldCreateItemWithValidListAndCreator() {
        // Given: Item with valid list and creator
        ListItem item = new ListItem();
        item.setName("Arroz");
        item.setList(testList);
        item.setCreatedBy(testUser);
        item.setQuantity(2); // Campo específico de Compras

        // When: Save the item
        ListItem saved = listItemRepository.save(item);

        // Then: Item must be persisted with all fields
        assertNotNull(saved.getId());
        assertEquals("Arroz", saved.getName());
        assertEquals(2, saved.getQuantity());
        assertFalse(saved.isChecked());
        assertEquals(0, saved.getPosition());
        assertNotNull(saved.getCreatedAt(), "createdAt should be auto-generated by @PrePersist");
        assertNotNull(saved.getUpdatedAt(), "updatedAt should be auto-generated by @PrePersist");
        assertEquals(testList.getId(), saved.getList().getId());
        assertEquals(testUser.getId(), saved.getCreatedBy().getId());
    }

    @Test
    void shouldVerifyCascadeDeleteIsConfiguredInMigration() {
        // This test verifies CASCADE DELETE at database level using native SQL
        // JPA-level cascade testing requires complex transaction management and
        // can be brittle. Instead, we verify the database constraint directly.

        // Given: Item with valid list and creator
        ListItem item = new ListItem();
        item.setName("Cascade Test Item");
        item.setList(testList);
        item.setCreatedBy(testUser);
        ListItem saved = listItemRepository.saveAndFlush(item);
        UUID itemId = saved.getId();
        UUID listId = testList.getId();

        // Verify item exists
        assertTrue(listItemRepository.existsById(itemId));
        assertEquals(1, listItemRepository.countByListId(listId));

        // When: Delete list using native SQL (bypasses JPA cascade complexity)
        entityManager.createNativeQuery("DELETE FROM lists WHERE id = :listId")
            .setParameter("listId", listId)
            .executeUpdate();

        // Clear JPA cache to force fresh queries
        entityManager.flush();
        entityManager.clear();

        // Then: Item must be automatically deleted by database CASCADE constraint
        assertFalse(listItemRepository.existsById(itemId),
            "CASCADE DELETE: Item should be deleted when list is deleted");
        assertEquals(0, listItemRepository.countByListId(listId),
            "No items should remain after list CASCADE deletion");

        // The CASCADE DELETE is configured at database level in V4__create_list_items.sql:
        // CONSTRAINT fk_list_items_list FOREIGN KEY (list_id) REFERENCES lists(id) ON DELETE CASCADE
    }

    @Test
    void shouldFindItemsOrderedByPosition() {
        // Given: List with 3 items in different positions
        ListItem item1 = new ListItem();
        item1.setName("Primeiro");
        item1.setList(testList);
        item1.setCreatedBy(testUser);
        item1.setPosition(0);
        listItemRepository.save(item1);

        ListItem item2 = new ListItem();
        item2.setName("Segundo");
        item2.setList(testList);
        item2.setCreatedBy(testUser);
        item2.setPosition(1);
        listItemRepository.save(item2);

        ListItem item3 = new ListItem();
        item3.setName("Terceiro");
        item3.setList(testList);
        item3.setCreatedBy(testUser);
        item3.setPosition(2);
        listItemRepository.save(item3);

        // When: Find items ordered by position
        java.util.List<ListItem> items = listItemRepository.findByListIdOrderByPositionAsc(testList.getId());

        // Then: Items must be returned in position order
        assertEquals(3, items.size());
        assertEquals("Primeiro", items.get(0).getName());
        assertEquals("Segundo", items.get(1).getName());
        assertEquals("Terceiro", items.get(2).getName());
    }

    @Test
    void shouldSupportNullableFields() {
        // Given: Items with different nullable fields
        // position setada explicitamente em cada item: a constraint
        // uq_list_items_list_position (V18) rejeita mais de um item com a
        // mesma position na mesma lista, e o default da entidade é 0.
        ListItem shoppingItem = new ListItem();
        shoppingItem.setName("Arroz");
        shoppingItem.setList(testList);
        shoppingItem.setCreatedBy(testUser);
        shoppingItem.setQuantity(5); // Compras: quantity
        shoppingItem.setPosition(0);
        listItemRepository.save(shoppingItem);

        ListItem taskItem = new ListItem();
        taskItem.setName("Fazer compras");
        taskItem.setList(testList);
        taskItem.setCreatedBy(testUser);
        taskItem.setDueDate(LocalDateTime.now().plusDays(1)); // Tarefas: dueDate
        taskItem.setPosition(1);
        listItemRepository.save(taskItem);

        ListItem wishlistItem = new ListItem();
        wishlistItem.setName("Cadeira Gamer");
        wishlistItem.setList(testList);
        wishlistItem.setCreatedBy(testUser);
        wishlistItem.setUrl("https://example.com/chair"); // Wishlist: url
        wishlistItem.setPosition(2);
        listItemRepository.save(wishlistItem);

        ListItem genericItem = new ListItem();
        genericItem.setName("Item genérico");
        genericItem.setList(testList);
        genericItem.setCreatedBy(testUser);
        // Genérica: sem campos especiais
        genericItem.setPosition(3);
        listItemRepository.save(genericItem);

        // When/Then: Verify all items saved correctly with nullable fields
        assertEquals(4, listItemRepository.count());

        ListItem savedShopping = listItemRepository.findById(shoppingItem.getId()).orElseThrow();
        assertEquals(5, savedShopping.getQuantity());
        assertNull(savedShopping.getDueDate());
        assertNull(savedShopping.getUrl());

        ListItem savedTask = listItemRepository.findById(taskItem.getId()).orElseThrow();
        assertNull(savedTask.getQuantity());
        assertNotNull(savedTask.getDueDate());
        assertNull(savedTask.getUrl());

        ListItem savedWishlist = listItemRepository.findById(wishlistItem.getId()).orElseThrow();
        assertNull(savedWishlist.getQuantity());
        assertNull(savedWishlist.getDueDate());
        assertEquals("https://example.com/chair", savedWishlist.getUrl());

        ListItem savedGeneric = listItemRepository.findById(genericItem.getId()).orElseThrow();
        assertNull(savedGeneric.getQuantity());
        assertNull(savedGeneric.getDueDate());
        assertNull(savedGeneric.getUrl());
    }

    @Test
    void shouldUpdateUpdatedAtOnModify() {
        // Given: Item created - @PrePersist sets timestamps
        ListItem item = new ListItem();
        item.setName("Original Name");
        item.setList(testList);
        item.setCreatedBy(testUser);
        ListItem saved = listItemRepository.saveAndFlush(item);
        LocalDateTime originalUpdatedAt = saved.getUpdatedAt();

        // When: Wait and modify
        try {
            Thread.sleep(100); // Ensure timestamp difference
        } catch (InterruptedException e) {
            // Ignore
        }
        saved.setName("Updated Name");
        ListItem updated = listItemRepository.saveAndFlush(saved);

        // Then: @PreUpdate must update updatedAt automatically
        assertTrue(updated.getUpdatedAt().isAfter(originalUpdatedAt),
            "@PreUpdate should auto-update updatedAt");
    }

    @Test
    void shouldFindByIdAndListId() {
        // Given: Item in test list
        ListItem item = new ListItem();
        item.setName("Test Item");
        item.setList(testList);
        item.setCreatedBy(testUser);
        ListItem saved = listItemRepository.save(item);

        // When: Find by id and listId
        Optional<ListItem> found = listItemRepository.findByIdAndListId(saved.getId(), testList.getId());

        // Then: Must find the item
        assertTrue(found.isPresent());
        assertEquals("Test Item", found.get().getName());
    }

    @Test
    void shouldNotFindWhenListIdMismatch() {
        // Given: Item in test list
        ListItem item = new ListItem();
        item.setName("Test Item");
        item.setList(testList);
        item.setCreatedBy(testUser);
        ListItem saved = listItemRepository.save(item);

        // When: Find with wrong listId
        Optional<ListItem> found = listItemRepository.findByIdAndListId(saved.getId(), UUID.randomUUID());

        // Then: Must not find
        assertFalse(found.isPresent());
    }

    @Test
    void shouldCountItemsByListId() {
        // Given: Multiple items in list (position distinta — ver
        // uq_list_items_list_position, V18)
        ListItem item1 = new ListItem();
        item1.setName("Item 1");
        item1.setList(testList);
        item1.setCreatedBy(testUser);
        item1.setPosition(0);
        listItemRepository.save(item1);

        ListItem item2 = new ListItem();
        item2.setName("Item 2");
        item2.setList(testList);
        item2.setCreatedBy(testUser);
        item2.setPosition(1);
        listItemRepository.save(item2);

        // When: Count by listId
        Long count = listItemRepository.countByListId(testList.getId());

        // Then: Must return 2
        assertEquals(2, count);
    }

    @Test
    void shouldFindByIdWithDetails() {
        // Given: Item with list and creator
        ListItem item = new ListItem();
        item.setName("Detailed Item");
        item.setList(testList);
        item.setCreatedBy(testUser);
        ListItem saved = listItemRepository.save(item);

        // When: Find with details
        Optional<ListItem> found = listItemRepository.findByIdWithDetails(saved.getId());

        // Then: Must find with all relationships
        assertTrue(found.isPresent());
        assertNotNull(found.get().getList());
        assertNotNull(found.get().getCreatedBy());
        assertEquals(testList.getId(), found.get().getList().getId());
        assertEquals(testUser.getId(), found.get().getCreatedBy().getId());
    }

    @Test
    void shouldEnforceNotNullConstraintOnName() {
        // Given: Item without name
        ListItem item = new ListItem();
        item.setName(null); // Invalid
        item.setList(testList);
        item.setCreatedBy(testUser);

        // When/Then: Must throw constraint exception
        // Jakarta Validation intercepta antes do banco de dados
        assertThrows(jakarta.validation.ConstraintViolationException.class, () -> {
            listItemRepository.saveAndFlush(item);
        });
    }

    @Test
    void shouldEnforceForeignKeyConstraintOnList() {
        // Given: Create a transient List (not persisted, no ID)
        SharedList transientList = new SharedList();
        transientList.setName("Transient List");
        transientList.setTypeId(1);
        transientList.setOwner(testUser);
        // Not persisted - remains transient

        ListItem item = new ListItem();
        item.setName("Orphan Item");
        item.setCreatedBy(testUser);
        item.setList(transientList);

        // When/Then: Hibernate detects transient instance before flush
        // and throws InvalidDataAccessApiUsageException (wrapped TransientPropertyValueException)
        assertThrows(org.springframework.dao.InvalidDataAccessApiUsageException.class, () -> {
            listItemRepository.saveAndFlush(item);
        });
    }

    @Test
    void shouldEnforceForeignKeyConstraintOnCreator() {
        // Given: Create a transient User (not persisted, no ID)
        User transientUser = new User();
        transientUser.setUsername("transient");
        transientUser.setEmail("transient@test.com");
        transientUser.setAuthProvider(AuthProvider.EMAIL);
        // Not persisted - remains transient

        ListItem item = new ListItem();
        item.setName("Orphan Item");
        item.setList(testList);
        item.setCreatedBy(transientUser);

        // When/Then: Hibernate detects transient instance before flush
        // and throws InvalidDataAccessApiUsageException (wrapped TransientPropertyValueException)
        assertThrows(org.springframework.dao.InvalidDataAccessApiUsageException.class, () -> {
            listItemRepository.saveAndFlush(item);
        });
    }

    @Test
    void shouldDefaultCheckedToFalse() {
        // Given: Item without explicit checked value
        ListItem item = new ListItem();
        item.setName("Unchecked Item");
        item.setList(testList);
        item.setCreatedBy(testUser);

        // When: Save
        ListItem saved = listItemRepository.save(item);

        // Then: checked must default to false
        assertFalse(saved.isChecked());
    }

    @Test
    void shouldDefaultPositionToZero() {
        // Given: Item without explicit position
        ListItem item = new ListItem();
        item.setName("Item without position");
        item.setList(testList);
        item.setCreatedBy(testUser);

        // When: Save
        ListItem saved = listItemRepository.save(item);

        // Then: position must default to 0
        assertEquals(0, saved.getPosition());
    }

    @Test
    void shouldUpdateCheckedStatus() {
        // Given: Item created unchecked
        ListItem item = new ListItem();
        item.setName("Task");
        item.setList(testList);
        item.setCreatedBy(testUser);
        ListItem saved = listItemRepository.save(item);
        assertFalse(saved.isChecked());

        // When: Mark as checked
        saved.setChecked(true);
        ListItem updated = listItemRepository.saveAndFlush(saved);

        // Then: Must be checked
        assertTrue(updated.isChecked());
    }
}
