package br.com.leoferolive.nossalista.user.repository;

import br.com.leoferolive.nossalista.user.domain.AuthProvider;
import br.com.leoferolive.nossalista.user.domain.Role;
import br.com.leoferolive.nossalista.user.domain.User;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Testes de integração para UserRepository
 */
@SpringBootTest
@Sql(scripts = "/db/migration/V1__create_users_table.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_CLASS)
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_CLASS)
@Transactional
class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private EntityManager entityManager;

    @Test
    void shouldSaveUserWithAutoGeneratedId() {
        // Given
        User user = new User();
        user.setUsername("testuser");
        user.setEmail("test@example.com");
        user.setPassword("hashedPassword");
        user.setAuthProvider(AuthProvider.EMAIL);

        // When
        User saved = userRepository.save(user);

        // Then
        assertThat(saved.getId()).isNotNull();
        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getUpdatedAt()).isNotNull();
        assertThat(saved.getCreatedAt()).isEqualTo(saved.getUpdatedAt());
    }

    @Test
    void shouldFindUserByEmail() {
        // Given
        User user = createTestUser("leo@example.com", "leoferolive");
        userRepository.save(user);

        // When
        var found = userRepository.findByEmail("leo@example.com");

        // Then
        assertThat(found).isPresent();
        assertThat(found.get().getUsername()).isEqualTo("leoferolive");
    }

    @Test
    void shouldFindUserByUsername() {
        // Given
        User user = createTestUser("user@example.com", "johndoe");
        userRepository.save(user);

        // When
        var found = userRepository.findByUsername("johndoe");

        // Then
        assertThat(found).isPresent();
        assertThat(found.get().getEmail()).isEqualTo("user@example.com");
    }

    @Test
    void shouldReturnTrueIfEmailExists() {
        // Given
        User user = createTestUser("existing@example.com", "user1");
        userRepository.save(user);

        // When
        boolean exists = userRepository.existsByEmail("existing@example.com");

        // Then
        assertThat(exists).isTrue();
    }

    @Test
    void shouldReturnFalseIfEmailDoesNotExist() {
        // When
        boolean exists = userRepository.existsByEmail("nonexistent@example.com");

        // Then
        assertThat(exists).isFalse();
    }

    @Test
    void shouldReturnTrueIfUsernameExists() {
        // Given
        User user = createTestUser("user@example.com", "existinguser");
        userRepository.save(user);

        // When
        boolean exists = userRepository.existsByUsername("existinguser");

        // Then
        assertThat(exists).isTrue();
    }

    @Test
    void shouldReturnFalseIfUsernameDoesNotExist() {
        // When
        boolean exists = userRepository.existsByUsername("nonexistentuser");

        // Then
        assertThat(exists).isFalse();
    }

    @Test
    void shouldUpdateTimestampOnUpdate() throws InterruptedException {
        // Given
        User user = createTestUser("update@example.com", "updateuser");
        User saved = userRepository.save(user);
        entityManager.flush();
        LocalDateTime originalUpdatedAt = saved.getUpdatedAt();

        // Sleep to ensure different timestamp
        Thread.sleep(10);

        // When
        saved.setName("Updated Name");
        User updated = userRepository.save(saved);
        entityManager.flush();

        // Then
        assertThat(updated.getUpdatedAt()).isAfter(originalUpdatedAt);
        assertThat(updated.getCreatedAt()).isEqualTo(saved.getCreatedAt());
    }

    private User createTestUser(String email, String username) {
        User user = new User();
        user.setEmail(email);
        user.setUsername(username);
        user.setPassword("hashedPassword");
        user.setAuthProvider(AuthProvider.EMAIL);
        user.setRole(Role.USER);
        return user;
    }
}
