package br.com.leoferolive.nossalista.push;

import br.com.leoferolive.nossalista.support.AbstractPostgresIT;
import br.com.leoferolive.nossalista.user.domain.AuthProvider;
import br.com.leoferolive.nossalista.user.domain.Role;
import br.com.leoferolive.nossalista.user.domain.User;
import br.com.leoferolive.nossalista.user.repository.UserRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Testes de integração para {@link PushSubscriptionRepository}.
 * Flyway auto-executa a migration V16 — não precisa de {@code @Sql} manual.
 *
 * <p>Estende {@link AbstractPostgresIT}: roda contra PostgreSQL real
 * (Testcontainers), não H2 — ver T1 da Onda 2 (honestidade de métrica).</p>
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class PushSubscriptionRepositoryTest extends AbstractPostgresIT {

    private static final AtomicInteger COUNTER = new AtomicInteger();

    @Autowired
    private PushSubscriptionRepository repository;

    @Autowired
    private UserRepository userRepository;

    /** push_subscriptions.user_id tem FK para users(id): cada teste precisa de um usuário real. */
    private UUID persistUser() {
        int n = COUNTER.incrementAndGet();
        User user = new User();
        user.setUsername("push-repo-user-" + n);
        user.setEmail("push-repo-user-" + n + "@example.com");
        user.setPassword("$2a$10$dummyHashForTesting");
        user.setAuthProvider(AuthProvider.EMAIL);
        user.setRole(Role.USER);
        return userRepository.saveAndFlush(user).getId();
    }

    @Test
    void shouldSaveSubscriptionWithAutoGeneratedIdAndTimestamps() {
        PushSubscriptionEntity entity = newEntity(persistUser(), "https://endpoint.com");

        PushSubscriptionEntity saved = repository.save(entity);

        assertThat(saved.getId()).isNotNull();
        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getUpdatedAt()).isEqualTo(saved.getCreatedAt());
    }

    @Test
    void shouldFindByUserIdOrderedByUpdatedAtAsc() throws InterruptedException {
        UUID userId = persistUser();
        repository.saveAndFlush(newEntity(userId, "https://endpoint-1.com"));
        Thread.sleep(10);
        repository.saveAndFlush(newEntity(userId, "https://endpoint-2.com"));

        List<PushSubscriptionEntity> found = repository.findByUserIdOrderByUpdatedAtAsc(userId);

        assertThat(found).hasSize(2);
        assertThat(found).extracting(PushSubscriptionEntity::getEndpoint)
            .containsExactly("https://endpoint-1.com", "https://endpoint-2.com");
    }

    @Test
    void shouldFindByEndpoint() {
        UUID userId = persistUser();
        repository.save(newEntity(userId, "https://endpoint.com"));

        var found = repository.findByEndpoint("https://endpoint.com");

        assertThat(found).isPresent();
        assertThat(found.get().getUserId()).isEqualTo(userId);
    }

    @Test
    void shouldNotAllowDuplicateEndpoint() {
        UUID userId = persistUser();
        repository.saveAndFlush(newEntity(userId, "https://endpoint-dup.com"));

        assertThat(repository.findByEndpoint("https://endpoint-dup.com")).isPresent();

        PushSubscriptionEntity duplicate = newEntity(persistUser(), "https://endpoint-dup.com");
        assertThat(repository.count()).isEqualTo(1);

        org.junit.jupiter.api.Assertions.assertThrows(
            org.springframework.dao.DataIntegrityViolationException.class,
            () -> repository.saveAndFlush(duplicate)
        );
    }

    @Test
    void shouldDeleteByUserIdAndEndpoint() {
        UUID userId = persistUser();
        repository.save(newEntity(userId, "https://endpoint.com"));

        repository.deleteByUserIdAndEndpoint(userId, "https://endpoint.com");

        assertThat(repository.findByUserIdOrderByUpdatedAtAsc(userId)).isEmpty();
    }

    @Test
    void shouldDeleteByUserId() {
        UUID userId = persistUser();
        repository.save(newEntity(userId, "https://endpoint-1.com"));
        repository.save(newEntity(userId, "https://endpoint-2.com"));

        repository.deleteByUserId(userId);

        assertThat(repository.findByUserIdOrderByUpdatedAtAsc(userId)).isEmpty();
    }

    private PushSubscriptionEntity newEntity(UUID userId, String endpoint) {
        PushSubscriptionEntity entity = new PushSubscriptionEntity();
        entity.setUserId(userId);
        entity.setEndpoint(endpoint);
        entity.setP256dh("p256dh");
        entity.setAuth("auth");
        return entity;
    }
}
