package br.com.leoferolive.nossalista.list.repository;

import br.com.leoferolive.nossalista.list.domain.List;
import br.com.leoferolive.nossalista.list.domain.ListType;
import br.com.leoferolive.nossalista.list.domain.ListTypeEntity;
import br.com.leoferolive.nossalista.user.domain.AuthProvider;
import br.com.leoferolive.nossalista.user.domain.Role;
import br.com.leoferolive.nossalista.user.domain.User;
import br.com.leoferolive.nossalista.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for ListRepository and validation of constraints
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class ListRepositoryTest {

    @Autowired
    private ListRepository listRepository;

    @Autowired
    private ListTypeRepository listTypeRepository;

    @Autowired
    private UserRepository userRepository;

    private User testUser;

    @BeforeEach
    void setUp() {
        // Create and persist test user - @PrePersist will set ID and timestamps
        testUser = new User();
        testUser.setUsername("testuser_" + System.currentTimeMillis()); // Unique username
        testUser.setEmail("test_" + System.currentTimeMillis() + "@example.com"); // Unique email
        testUser.setAuthProvider(AuthProvider.EMAIL);
        testUser.setPassword("$2a$10$dummyHashForTesting"); // Required for EMAIL provider
        testUser.setRole(Role.USER);
        testUser = userRepository.saveAndFlush(testUser); // Force immediate persist
    }

    @Test
    void shouldCreateListWithValidTypeAndOwner() {
        // Given: List with valid type and owner - @PrePersist will set timestamps
        List list = new List();
        list.setName("Weekly Market");
        list.setTypeId(1); // Shopping
        list.setOwner(testUser);

        // When: Save the list
        List saved = listRepository.save(list);

        // Then: List must be persisted with fields populated (including auto-generated timestamps)
        assertNotNull(saved.getId());
        assertEquals("Weekly Market", saved.getName());
        assertEquals(1, saved.getTypeId());
        assertEquals(testUser.getId(), saved.getOwner().getId());
        assertNotNull(saved.getCreatedAt(), "createdAt should be auto-generated by @PrePersist");
        assertNotNull(saved.getUpdatedAt(), "updatedAt should be auto-generated by @PrePersist");
    }

    @Test
    @Disabled("Cascade delete works at DB level (ON DELETE CASCADE) but is complex to test in JPA due to entity state management")
    void shouldCascadeDeleteListsWhenOwnerDeleted() {
        // Given: Create a separate user for this test to avoid transaction conflicts
        User ownerUser = new User();
        ownerUser.setUsername("deletetest_" + System.currentTimeMillis());
        ownerUser.setEmail("deletetest_" + System.currentTimeMillis() + "@example.com");
        ownerUser.setAuthProvider(AuthProvider.EMAIL);
        ownerUser.setPassword("$2a$10$dummyHashForTesting");
        ownerUser.setRole(Role.USER);
        ownerUser = userRepository.saveAndFlush(ownerUser);

        UUID ownerId = ownerUser.getId();

        // Create list for this user
        List list = new List();
        list.setName("Test List");
        list.setTypeId(1);
        list.setOwner(ownerUser);
        listRepository.saveAndFlush(list);

        assertEquals(1, listRepository.findByOwnerId(ownerId).size());

        // When: Delete the user (should cascade delete lists)
        userRepository.delete(ownerUser);
        userRepository.flush();

        // Then: Lists should be deleted due to ON DELETE CASCADE
        assertEquals(0, listRepository.findByOwnerId(ownerId).size());
    }

    @Test
    void shouldEnforceUniqueInviteCode() {
        // Given: First list with invite code
        List list1 = new List();
        list1.setName("List 1");
        list1.setTypeId(1);
        list1.setOwner(testUser);
        list1.setInviteCode("ABC123");
        listRepository.saveAndFlush(list1); // Force persist to check constraint

        // When/Then: Second list with same invite code should fail
        List list2 = new List();
        list2.setName("List 2");
        list2.setTypeId(2);
        list2.setOwner(testUser);
        list2.setInviteCode("ABC123"); // Duplicated

        assertThrows(org.springframework.dao.DataIntegrityViolationException.class, () -> {
            listRepository.saveAndFlush(list2); // Force flush to trigger constraint
        });
    }

    @Test
    void shouldFindListsByOwnerId() {
        // Given: Two lists from same user
        List list1 = new List();
        list1.setName("List 1");
        list1.setTypeId(1);
        list1.setOwner(testUser);
        listRepository.save(list1);

        List list2 = new List();
        list2.setName("List 2");
        list2.setTypeId(2);
        list2.setOwner(testUser);
        listRepository.save(list2);

        // When: Find lists by user
        java.util.List<List> lists = listRepository.findByOwnerId(testUser.getId());

        // Then: Both lists must be returned
        assertEquals(2, lists.size());
    }

    @Test
    void shouldFindByInviteCode() {
        // Given: List with invite code
        List list = new List();
        list.setName("Shared List");
        list.setTypeId(3);
        list.setOwner(testUser);
        list.setInviteCode("SHARE123");
        listRepository.save(list);

        // When: Find by invite code
        java.util.Optional<List> found = listRepository.findByInviteCode("SHARE123");

        // Then: List must be found
        assertTrue(found.isPresent());
        assertEquals("Shared List", found.get().getName());
    }

    @Test
    void shouldReturnEmptyWhenInviteCodeNotFound() {
        // When: Find by non-existent invite code
        java.util.Optional<List> found = listRepository.findByInviteCode("NOTEXIST");

        // Then: Must return empty
        assertFalse(found.isPresent());
    }

    @Test
    void shouldHaveFourListTypesAfterMigration() {
        // When: Count list types
        long count = listTypeRepository.count();

        // Then: Must have exactly 4 predefined types
        assertEquals(4, count);
    }

    @Test
    void shouldHaveCorrectListTypeSlugs() {
        // Given: Find all types
        java.util.List<ListTypeEntity> types = listTypeRepository.findAll();

        // When: Extract slugs
        java.util.List<String> slugs = types.stream()
                .map(ListTypeEntity::getSlug)
                .sorted()
                .toList();

        // Then: Must contain the 4 types in correct order
        assertEquals(java.util.List.of("compras", "generica", "tarefas", "wishlist"), slugs);
    }

    @Test
    void shouldUpdateUpdatedAtOnModify() {
        // Given: List created - @PrePersist sets timestamps
        List list = new List();
        list.setName("Original Name");
        list.setTypeId(1);
        list.setOwner(testUser);
        List saved = listRepository.saveAndFlush(list); // Force persist
        LocalDateTime originalUpdatedAt = saved.getUpdatedAt();

        // When: Wait and modify
        try {
            Thread.sleep(100); // Ensure timestamp difference
        } catch (InterruptedException e) {
            // Ignore
        }
        saved.setName("Updated Name");
        List updated = listRepository.saveAndFlush(saved); // Force update with @PreUpdate

        // Then: @PreUpdate must update updatedAt automatically
        assertTrue(updated.getUpdatedAt().isAfter(originalUpdatedAt),
            "@PreUpdate should auto-update updatedAt. Original: " + originalUpdatedAt + ", Updated: " + updated.getUpdatedAt());
    }

    @Test
    void shouldNotAllowInvalidTypeId() {
        // Given: List with invalid typeId
        List list = new List();
        list.setName("Invalid Type List");
        list.setTypeId(999); // Does not exist in list_types table
        list.setOwner(testUser);

        // When/Then: Must throw FK constraint exception
        assertThrows(org.springframework.dao.DataIntegrityViolationException.class, () -> {
            listRepository.saveAndFlush(list); // Force flush to trigger FK constraint
        });
    }

    @Test
    void shouldConvertFromSlugCorrectly() {
        // Given/When/Then: Test slug to ListType conversion
        assertEquals(ListType.SHOPPING, ListType.fromSlug("compras"));
        assertEquals(ListType.TASK, ListType.fromSlug("tarefas"));
        assertEquals(ListType.WISHLIST, ListType.fromSlug("wishlist"));
        assertEquals(ListType.GENERIC, ListType.fromSlug("generica"));
    }

    @Test
    void shouldThrowExceptionForInvalidSlug() {
        // When/Then: Invalid slug must throw exception
        assertThrows(IllegalArgumentException.class, () -> {
            ListType.fromSlug("invalid");
        });
    }

    @Test
    void shouldReturnTypeFromListEntity() {
        // Given: List with typeId 1 (Shopping)
        List list = new List();
        list.setTypeId(1);

        // When: Get type
        ListType type = list.getType();

        // Then: Must return SHOPPING
        assertEquals(ListType.SHOPPING, type);
    }

    @Test
    void shouldReturnTypeFromListEntityWhenTypeEntityLoaded() {
        // Given: ListTypeEntity with slug "compras"
        ListTypeEntity typeEntity = listTypeRepository.findBySlug("compras").orElseThrow();

        List list = new List();
        list.setTypeId(typeEntity.getId());
        list.setTypeEntity(typeEntity);

        // When: Get type
        ListType type = list.getType();

        // Then: Must return SHOPPING
        assertEquals(ListType.SHOPPING, type);
    }
}
