name: Deploy Prod (nossalista.leoferolive.com.br)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Digite 'deploy' para confirmar o deploy em produção"
        required: true
        type: string

jobs:
  check-confirm:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar confirmação
        if: ${{ inputs.confirm != 'deploy' }}
        run: |
          echo "Confirmação inválida. Digite 'deploy' para prosseguir."
          exit 1

  deploy:
    needs: check-confirm
    uses: leoferolive/self-workflows/.github/workflows/deploy.yml@main
    with:
      app_name: nossalista
      app_namespace: nossalista
      app_type: backend
      dockerfile_path: ./Dockerfile
      k8s_path: ./k8s/prod
      image_tag: latest
    secrets: inherit
